package Principal;

import TXT.LoginTXT;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author JafetDG
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        setLocationRelativeTo(null);
        setIconImage(getIconImage());

    }

    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icon1.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrincipal = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtPassword = new javax.swing.JPasswordField();
        TxtUsername = new javax.swing.JTextField();
        BtnEnter = new javax.swing.JButton();
        LblError = new javax.swing.JLabel();
        BtnSalir2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelPrincipal.setBackground(new java.awt.Color(204, 204, 204));
        JPanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Credits.png"))); // NOI18N
        JPanelPrincipal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 470, 100, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestor de Eventos");
        JPanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Iniciar Sesión");
        JPanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Usuario:");
        JPanelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 34));

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contraseña:");
        JPanelPrincipal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        TxtPassword.setBackground(new java.awt.Color(255, 255, 255));
        TxtPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TxtPassword.setForeground(new java.awt.Color(0, 0, 0));
        TxtPassword.setText("1234567");
        TxtPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        TxtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtPasswordMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtPasswordMouseExited(evt);
            }
        });
        JPanelPrincipal.add(TxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 197, 34));

        TxtUsername.setBackground(new java.awt.Color(255, 255, 255));
        TxtUsername.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TxtUsername.setForeground(new java.awt.Color(0, 0, 0));
        TxtUsername.setText("Nombre de usuario");
        TxtUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtUsernameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TxtUsernameMouseExited(evt);
            }
        });
        JPanelPrincipal.add(TxtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 197, 34));

        BtnEnter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BtnEnter.setForeground(new java.awt.Color(0, 0, 0));
        BtnEnter.setText("Ingresar");
        BtnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEnterActionPerformed(evt);
            }
        });
        JPanelPrincipal.add(BtnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, 270, 34));

        LblError.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        LblError.setForeground(new java.awt.Color(255, 0, 0));
        LblError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JPanelPrincipal.add(LblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 380, 281, 30));

        BtnSalir2.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BtnSalir2.setForeground(new java.awt.Color(0, 0, 0));
        BtnSalir2.setText("Salir");
        BtnSalir2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalir2ActionPerformed(evt);
            }
        });
        JPanelPrincipal.add(BtnSalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 410, 80, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo Login.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        JPanelPrincipal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 490));

        getContentPane().add(JPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEnterActionPerformed

        String nombreUsuario = TxtUsername.getText();
        String contrasena = TxtPassword.getText();

        boolean usuarioValido = LoginTXT.validarUsuario(nombreUsuario, contrasena);

        if (usuarioValido) {
            JOptionPane.showMessageDialog(this, "¡Bienvenido, " + nombreUsuario + "!");
            FrmPrincipal princi = new FrmPrincipal();
            princi.setVisible(true);
            dispose();
        } else {
            LblError.setText("¡Credenciales Incorrectas!");
        }


    }//GEN-LAST:event_BtnEnterActionPerformed

    private void TxtUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtUsernameMouseClicked
        VaciarDataUsuario();
    }//GEN-LAST:event_TxtUsernameMouseClicked

    private void TxtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPasswordMouseClicked
        VaciarDataContra();
    }//GEN-LAST:event_TxtPasswordMouseClicked

    private void TxtUsernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtUsernameMouseExited
        if (TxtUsername.getText().equals("")) {
            TxtUsername.setText("Nombre de usuario");
        }
    }//GEN-LAST:event_TxtUsernameMouseExited

    private void TxtPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPasswordMouseExited
        if (TxtPassword.getText().equals("")) {
            TxtPassword.setText("1234567");
        }
    }//GEN-LAST:event_TxtPasswordMouseExited

    private void BtnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalir2ActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;

        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir del gestor?", "Exit", dialog);

        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnSalir2ActionPerformed

    public void VaciarDataUsuario() {
        TxtUsername.setText("");
    }

    public void VaciarDataContra() {
        TxtPassword.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEnter;
    private javax.swing.JButton BtnSalir2;
    private javax.swing.JPanel JPanelPrincipal;
    private javax.swing.JLabel LblError;
    private javax.swing.JPasswordField TxtPassword;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
