package Principal;

import Datos.TicketComprado;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex Guevara
 */


public class JFrameVendidos extends javax.swing.JFrame { 
    /*--------------------------------------------------------------------------*/
    static List<TicketComprado> pilavendidos;
    /*--------------------------------------------------------------------------*/
    
    String Nombre;
    String Fecha;
    String Hora;
    int TotalEntrada;
    int EntradasDisponibles;

    /**
     * Creates new form JFrameTeatral
     */
    public JFrameVendidos() {
        initComponents();
        setLocationRelativeTo(null);
        cargarVendidos();   
        actualizarTablaVendidos();
        setIconImage(getIconImage());
        setLocationRelativeTo(null);
        /* Deshabilita el boton de comprar hasta que se vaya a hacer una compra */
            
    }
    
      @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icon1.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_Evento = new javax.swing.JLabel();
        ScrollVendido = new javax.swing.JScrollPane();
        tableVendidos = new javax.swing.JTable();
        BtnVolver = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestor de Eventos");

        lbl_Evento.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbl_Evento.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Evento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Evento.setText("Vendidos");

        tableVendidos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tableVendidos.setForeground(new java.awt.Color(0, 0, 0));
        tableVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Hora", "Bloque", "Asiento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVendidos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tableVendidos.setDragEnabled(true);
        tableVendidos.setGridColor(new java.awt.Color(0, 0, 0));
        tableVendidos.setShowGrid(true);
        tableVendidos.getTableHeader().setReorderingAllowed(false);
        ScrollVendido.setViewportView(tableVendidos);

        BtnVolver.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(0, 0, 0));
        BtnVolver.setText("Volver");
        BtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        BtnSalir.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(0, 0, 0));
        BtnSalir.setText("Salir");
        BtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelPrincipalLayout = new javax.swing.GroupLayout(JPanelPrincipal);
        JPanelPrincipal.setLayout(JPanelPrincipalLayout);
        JPanelPrincipalLayout.setHorizontalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(93, 93, 93))
            .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lbl_Evento, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ScrollVendido, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
        );
        JPanelPrincipalLayout.setVerticalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Evento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnSalir))
            .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                    .addGap(105, 105, 105)
                    .addComponent(ScrollVendido, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addGap(105, 105, 105)))
        );

        getContentPane().add(JPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 420, 410));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Credits.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo Vendidos.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        FrmPrincipal p = new FrmPrincipal();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;

        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir del gestor?", "Exit", dialog);

        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnSalirActionPerformed

      
    private void cargarVendidos() {
        pilavendidos = TXT.EventoTXT.LeerComprados();
        
    }
    
    /*--------------------------------------------------------------------------*/
    
    private void actualizarTablaVendidos() {

        if (pilavendidos != null && !pilavendidos.isEmpty()) {

            DefaultTableModel model = (DefaultTableModel) this.tableVendidos.getModel();
            model.setNumRows(0);

            for (TicketComprado event : pilavendidos) {
                Object[] fila = new Object[5];
                fila[0] = event.getNombre();
                fila[1] = event.getFecha();
                fila[2] = event.getHora();
                fila[3] = event.getBloque();
                fila[4] = event.getNumero();

                model.addRow(fila);
            }

        }
    }
   
    /*--------------------------------------------------------------------------*/
    
    
    public List filtradoPila() {
        List<TicketComprado> vendidosFilter = pilavendidos.stream().filter(item -> {

            return "Teatrales".equals(lbl_Evento.getText());

        }).collect(Collectors.toList());

        return vendidosFilter;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameVendidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JPanel JPanelPrincipal;
    private javax.swing.JScrollPane ScrollVendido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbl_Evento;
    private javax.swing.JTable tableVendidos;
    // End of variables declaration//GEN-END:variables
}
