package GestorEventos;

import Datos.Evento;
import Principal.FrmPrincipal;
import TXT.EventoTXT;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex Guevara
 */
public class JFrameEventos extends javax.swing.JFrame {

    static ArrayList<Evento> eventos = new ArrayList<>();

    String tipoEvento;

    /**
     * Creates new form JFrameTeatral
     */
    public JFrameEventos(String tipoEv) {
        initComponents();
        setLocationRelativeTo(null);
        lbl_Evento.setText(tipoEv);
        tipoEvento = tipoEv;
        CargarData();
        actualizarTabla();
        setIconImage(getIconImage());
        setLocationRelativeTo(null);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource(cambioLabel())));

        table_Eventos.addMouseListener(
                new MouseAdapter() {
            DefaultTableModel model = new DefaultTableModel();

            @Override
            public void mouseClicked(MouseEvent e) {
                BtnComprar.setEnabled(true);
                int i = table_Eventos.getSelectedRow();
            }

        }
        );
    }

    @Override
    public Image getIconImage() {

        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("img/icon1.png"));

        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lbl_Evento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Eventos = new javax.swing.JTable();
        BtnComprar = new javax.swing.JButton();
        BtnVolver = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestor de Eventos");

        lbl_Evento.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lbl_Evento.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Evento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Evento.setText("Teatrales");

        table_Eventos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        table_Eventos.setForeground(new java.awt.Color(0, 0, 0));
        table_Eventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Fecha", "Hora", "Total Entradas", "Entradas Disponibles"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_Eventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        table_Eventos.setDragEnabled(true);
        table_Eventos.setGridColor(new java.awt.Color(0, 0, 0));
        table_Eventos.setShowGrid(true);
        table_Eventos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_Eventos);

        BtnComprar.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BtnComprar.setForeground(new java.awt.Color(0, 0, 0));
        BtnComprar.setText("Comprar");
        BtnComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnComprar.setEnabled(false);
        BtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarActionPerformed(evt);
            }
        });

        BtnVolver.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BtnVolver.setForeground(new java.awt.Color(0, 0, 0));
        BtnVolver.setText("Volver");
        BtnVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVolverActionPerformed(evt);
            }
        });

        BtnSalir.setFont(new java.awt.Font("Segoe UI Black", 2, 18)); // NOI18N
        BtnSalir.setForeground(new java.awt.Color(0, 0, 0));
        BtnSalir.setText("Salir");
        BtnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelPrincipalLayout = new javax.swing.GroupLayout(JPanelPrincipal);
        JPanelPrincipal.setLayout(JPanelPrincipalLayout);
        JPanelPrincipalLayout.setHorizontalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(BtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnComprar)
                        .addGap(26, 26, 26)
                        .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 99, Short.MAX_VALUE)
                        .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_Evento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(93, 93, 93))))
        );
        JPanelPrincipalLayout.setVerticalGroup(
            JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelPrincipalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Evento)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnVolver, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BtnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );

        getContentPane().add(JPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 420, 410));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Credits.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fondo Teatral.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarActionPerformed
        int i = table_Eventos.getSelectedRow();
        int entradaDisponible = Integer.parseInt(table_Eventos.getValueAt(i, 4).toString());
        if (entradaDisponible == 0) {
            JOptionPane.showMessageDialog(null, "No hay tickets disponibles");

        } else {
            FrmCompraTickets ctm = new FrmCompraTickets(tipoEvento);
            ctm.setVisible(true);

            ctm.nombreEvento =(table_Eventos.getValueAt(i, 0).toString());
            ctm.LblNombreEvento.setText(ctm.nombreEvento);
            ctm.LblFechaEvento.setText(table_Eventos.getValueAt(i, 1).toString());
            ctm.LblHora.setText(table_Eventos.getValueAt(i, 2).toString());
            ctm.generaBotonesBloque();
            ctm.activaListenerBloque();
            this.setVisible(false);

            dispose();
        }
    }//GEN-LAST:event_BtnComprarActionPerformed

    private void BtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVolverActionPerformed
        FrmPrincipal p = new FrmPrincipal();
        p.setVisible(true);
        dispose();
    }//GEN-LAST:event_BtnVolverActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        int dialog = JOptionPane.YES_NO_OPTION;

        int result = JOptionPane.showConfirmDialog(null, "¿Desea salir del gestor?", "Exit", dialog);

        if (result == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_BtnSalirActionPerformed

    public void CargarData() {
        eventos = TXT.EventoTXT.LeerData();
    }

    private void actualizarTabla() {
        List<Evento> eventosFiltrados = filtradoLista();

        if (eventosFiltrados != null && !eventosFiltrados.isEmpty()) {

            DefaultTableModel model = (DefaultTableModel) this.table_Eventos.getModel();
            model.setNumRows(0);

            for (Evento event : eventosFiltrados) {
                Object[] fila = new Object[5];
                fila[0] = event.getNombre();
                fila[1] = EventoTXT.convertirFechaTipoDate(event.getFecha());
                fila[2] = event.getHora();
                fila[3] = event.getTotalEntradas();
                fila[4] = event.getEntradasDisponibles();

                model.addRow(fila);
            }

        }
    }

    public List filtradoLista() {
        List<Evento> eventosFilter = eventos.stream().filter(item -> {

            return item.getTipoEvento().equals(tipoEvento);

        }).sorted(Comparator.comparing(Evento::getFecha).reversed()).collect(Collectors.toList());

        return eventosFilter;
    }

    public String cambioLabel() {
        String labelDefault = "/img/Fondo Otros Eventos.png";

        HashMap<String, String> hashLabel = new HashMap<>();

        hashLabel.put("Teatrales", "/img/Fondo Teatral.png");
        hashLabel.put("Comedias", "/img/Fondo Comedia.png");
        hashLabel.put("Musicales", "/img/Fondo Musical.png");
        hashLabel.put("Deportivos", "/img/Fondo Deportivo.png");

        return hashLabel.getOrDefault(tipoEvento, labelDefault);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            System.err.println("Failed to initialize LaF");
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameEventos("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnComprar;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnVolver;
    private javax.swing.JPanel JPanelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_Evento;
    private javax.swing.JTable table_Eventos;
    // End of variables declaration//GEN-END:variables
}
